/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as graphql from "@nestjs/graphql";
import * as apollo from "apollo-server-express";
import * as nestAccessControl from "nest-access-control";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import * as gqlUserRoles from "../../auth/gqlUserRoles.decorator";
import * as abacUtil from "../../auth/abac.util";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { CreatePartnerArgs } from "./CreatePartnerArgs";
import { UpdatePartnerArgs } from "./UpdatePartnerArgs";
import { DeletePartnerArgs } from "./DeletePartnerArgs";
import { PartnerFindManyArgs } from "./PartnerFindManyArgs";
import { PartnerFindUniqueArgs } from "./PartnerFindUniqueArgs";
import { Partner } from "./Partner";
import { CourseFindManyArgs } from "../../course/base/CourseFindManyArgs";
import { Course } from "../../course/base/Course";
import { PartnerService } from "../partner.service";

@graphql.Resolver(() => Partner)
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
export class PartnerResolverBase {
  constructor(
    protected readonly service: PartnerService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "Partner",
    action: "read",
    possession: "any",
  })
  async _partnersMeta(
    @graphql.Args() args: PartnerFindManyArgs
  ): Promise<MetaQueryPayload> {
    const results = await this.service.count({
      ...args,
      skip: undefined,
      take: undefined,
    });
    return {
      count: results,
    };
  }

  @graphql.Query(() => [Partner])
  @nestAccessControl.UseRoles({
    resource: "Partner",
    action: "read",
    possession: "any",
  })
  async partners(
    @graphql.Args() args: PartnerFindManyArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<Partner[]> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "any",
      resource: "Partner",
    });
    const results = await this.service.findMany(args);
    return results.map((result) => permission.filter(result));
  }

  @graphql.Query(() => Partner, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Partner",
    action: "read",
    possession: "own",
  })
  async partner(
    @graphql.Args() args: PartnerFindUniqueArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<Partner | null> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "own",
      resource: "Partner",
    });
    const result = await this.service.findOne(args);
    if (result === null) {
      return null;
    }
    return permission.filter(result);
  }

  @graphql.Mutation(() => Partner)
  @nestAccessControl.UseRoles({
    resource: "Partner",
    action: "create",
    possession: "any",
  })
  async createPartner(
    @graphql.Args() args: CreatePartnerArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<Partner> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "create",
      possession: "any",
      resource: "Partner",
    });
    const invalidAttributes = abacUtil.getInvalidAttributes(
      permission,
      args.data
    );
    if (invalidAttributes.length) {
      const properties = invalidAttributes
        .map((attribute: string) => JSON.stringify(attribute))
        .join(", ");
      const roles = userRoles
        .map((role: string) => JSON.stringify(role))
        .join(",");
      throw new apollo.ApolloError(
        `providing the properties: ${properties} on ${"Partner"} creation is forbidden for roles: ${roles}`
      );
    }
    // @ts-ignore
    return await this.service.create({
      ...args,
      data: args.data,
    });
  }

  @graphql.Mutation(() => Partner)
  @nestAccessControl.UseRoles({
    resource: "Partner",
    action: "update",
    possession: "any",
  })
  async updatePartner(
    @graphql.Args() args: UpdatePartnerArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<Partner | null> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "update",
      possession: "any",
      resource: "Partner",
    });
    const invalidAttributes = abacUtil.getInvalidAttributes(
      permission,
      args.data
    );
    if (invalidAttributes.length) {
      const properties = invalidAttributes
        .map((attribute: string) => JSON.stringify(attribute))
        .join(", ");
      const roles = userRoles
        .map((role: string) => JSON.stringify(role))
        .join(",");
      throw new apollo.ApolloError(
        `providing the properties: ${properties} on ${"Partner"} update is forbidden for roles: ${roles}`
      );
    }
    try {
      // @ts-ignore
      return await this.service.update({
        ...args,
        data: args.data,
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Partner)
  @nestAccessControl.UseRoles({
    resource: "Partner",
    action: "delete",
    possession: "any",
  })
  async deletePartner(
    @graphql.Args() args: DeletePartnerArgs
  ): Promise<Partner | null> {
    try {
      // @ts-ignore
      return await this.service.delete(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.ResolveField(() => [Course])
  @nestAccessControl.UseRoles({
    resource: "Partner",
    action: "read",
    possession: "any",
  })
  async courses(
    @graphql.Parent() parent: Partner,
    @graphql.Args() args: CourseFindManyArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<Course[]> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "any",
      resource: "Course",
    });
    const results = await this.service.findCourses(parent.id, args);

    if (!results) {
      return [];
    }

    return results.map((result) => permission.filter(result));
  }
}
