/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { CourseContentWhereUniqueInput } from "../../courseContent/base/CourseContentWhereUniqueInput";
import { ValidateNested, IsString, IsOptional } from "class-validator";
import { Type } from "class-transformer";
import { PartnerWhereUniqueInput } from "../../partner/base/PartnerWhereUniqueInput";
import { TopicCreateNestedManyWithoutCoursesInput } from "./TopicCreateNestedManyWithoutCoursesInput";
@InputType()
class CourseCreateInput {
  @ApiProperty({
    required: true,
    type: () => CourseContentWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => CourseContentWhereUniqueInput)
  @Field(() => CourseContentWhereUniqueInput)
  content!: CourseContentWhereUniqueInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  description?: string | null;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @Field(() => String)
  image!: string;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @Field(() => String)
  name!: string;

  @ApiProperty({
    required: true,
    type: () => PartnerWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => PartnerWhereUniqueInput)
  @Field(() => PartnerWhereUniqueInput)
  partner!: PartnerWhereUniqueInput;

  @ApiProperty({
    required: true,
    type: () => TopicCreateNestedManyWithoutCoursesInput,
  })
  @ValidateNested()
  @Type(() => TopicCreateNestedManyWithoutCoursesInput)
  @IsOptional()
  @Field(() => TopicCreateNestedManyWithoutCoursesInput, {
    nullable: true,
  })
  topics?: TopicCreateNestedManyWithoutCoursesInput;
}
export { CourseCreateInput };
